### PR TITLE
testing document rewrite

### PR DESCRIPTION
**Pull request by MichaelHochriegl**
- Restructured the headings based on Discord discussion
- Add passing down route parameters in Unit Tests

### CODE REVIEW

**Comment by CerealKiller97** [comment]
@MichaelHochriegl I think you should include a code (endpoint) for **GetUser** as well so people can see exactly, if they don't know.

**Comment by MichaelHochriegl** [comment]
Sorry for taking so long, just added a proper example for the route test. Will start working on the integration part now.

**Comment by CerealKiller97** [comment]
@MichaelHochriegl Perfect!

**Comment by dj-nitehawk** [comment]
@MichaelHochriegl merged...
thanks for contributing...
much appreciated :-)

**Pull request merged**
